[package]
name = "png"
version = "0.2.0"
license = "MIT"
description = "PNG decoding library"
authors = ["nwin <nwin@users.noreply.github.com>"]
repository = "https://github.com/nwin/png.git"
exclude = [
    "tests/*",
]

[dependencies]
flate2 = "*"
libc = "*"
num = "*"
bitflags = "*"

[dev-dependencies]
getopts = "*"
term = "0.2"
glob = "*"
rust-tcl = "*"
rust-tcl-sys = "*"

[dependencies.inflate]
path = "./inflate"