[package]
name = "png"
version = "0.3.1"
license = "MIT"
description = "PNG decoding library"
authors = ["nwin <nwin@users.noreply.github.com>"]
repository = "https://github.com/nwin/png.git"
exclude = [
    "tests/*",
]

[dependencies]
flate2 = "*"
libc = "*"
num = "*"
bitflags = "*"

# Development only
#[dependencies.inflate]
#path = "inflate"

[dev-dependencies]
getopts = "*"
term = "0.2"
glob = "*"

[dev-dependencies.glium]
version = "*"
features = ["glutin"]
default-features = false

[features]
default = []
unstable = []